apiVersion: v1
kind: ReplicationController
metadata:
  name: "ftpd-sever"
spec:
  replicas: 2 
  selector:
    app: "ftpd-server"
  template:
    metadata:
      name: "ftpd-server"
      labels:
        app: "ftpd-server"
    spec:
      restartPolicy: Always
      containers:
      - name: ftpd-server
        image: stilliard/pure-ftpd:hardened
        ports:
          - containerPort: 21
        command:
          - /run.sh
          - "-e 'PUBLICHOST=localhost'"
